name: Deploy AOI Study Hub
on:
  push:
    branches:
      - main
    paths:
      - docs/**
  # Also allows me to rebuild manually from the actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Not needed if lastUpdated is not enabled
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: pnpm/action-setup@v3
        with:
          version: 9 # Not needed if you've set "packageManager" in package.json
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
          cache-dependency-path: docs/pnpm-lock.yaml
      - name: Install dependencies
        run: cd docs && pnpm install
      - name: Build with VitePress
        run: cd docs && pnpm run docs:build
      - name: Add CNAME
        run: cp CNAME docs/.vitepress/dist/CNAME
      - name: Copy PDFs into dist
        run: |
          # make sure dist exists
          mkdir -p docs/.vitepress/dist
          # copy all PDFs preserving folder structure but stripping "docs/"
          rsync -av --prune-empty-dirs --include '*/' --include '*.pdf' --exclude '*' docs/ docs/.vitepress/dist/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/.vitepress/dist
